# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pwqxBHW-RLFdx0xPlqX7_1s8DtAjVooP
"""

import numpy as np
print("NumPy Version:", np.__version__)

import pandas as pd
print("Pandas Version:", pd.__version__)

import matplotlib
print("Matplotlib Version:", matplotlib.__version__)

import seaborn as sns
print("Seaborn Version:", sns.__version__)

import statsmodels
print("Statsmodels Version:", statsmodels.__version__)

import scipy
print("SciPy Version:", scipy.__version__)

import plotly
print("Plotly Version:", plotly.__version__)

import bokeh
print("Bokeh Version:", bokeh.__version__)

import jupyterlab
print("JupyterLab Version:", jupyterlab.__version__)

